create-repo-hw-solution
margosha99/online-book-store pull request #1
Opened 2024-10-18 10:43 UTC by margosha99

Configuration files added, Spring Boot project with Book entity created

2024-10-18 17:34 UTC, okuzan requested changes

2024-10-18 17:34 UTC, okuzan commented on src/main/java/com/example/demo/service/BookServiceImpl.java
> +        return null;
add implementations

2024-10-18 17:34 UTC, okuzan commented on src/main/java/com/example/demo/service/BookService.java
> +
```suggestion
```

2024-10-18 17:34 UTC, okuzan commented on src/main/java/com/example/demo/repository/BookRepositoryImpl.java
> +        return null;
add impl

2024-10-18 17:34 UTC, okuzan commented on src/main/java/com/example/demo/repository/BookRepository.java
> +
```suggestion
```

2024-10-18 17:34 UTC, okuzan commented on src/main/java/com/example/demo/repository/BookRepository.java
> +
```suggestion
```

2024-10-18 17:34 UTC, okuzan commented on src/main/java/com/example/demo/model/Book.java
> +
```suggestion
```

2024-10-18 17:34 UTC, okuzan commented on src/main/java/com/example/demo/model/Book.java
> +@Data
Don't use @Data on JPA entities, they contain @ToString and @EqualAndHashcode that can be problematic, use @ Getter @Setter here

2024-11-05 15:33 UTC, ahoienko approved these changes
Good job!

2024-11-06 13:06 UTC, merged